services: 
  application: # go backend application
    build: .
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=${GO_ENV}
      - PORT=${PORT}
      - DB_DSN=${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(db:3306)/${MYSQL_DATABASE}?charset=utf8mb4&parseTime=True&loc=Local
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
      - action: sync+restart
        path: ./
        target: ./app

  db: # Mysql db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - "../files/mysql-data:/var/lib/mysql" # Persist database data
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  db-data:  # Named volume for database persistence